#################################
#       Backend & General       #
#################################
backend = "glx";
vsync = true;
use-damage = true;
detect-client-opacity = true;
detect-rounded-corners = false;
dithered-present = true;

unredir-if-possible = true;
unredir-if-possible-delay = 500;

#################################
#         Animations            #
#################################
fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 12;

#################################
#            Shadows            #
#################################
shadow = false;

#################################
#             Blur              #
#################################
blur-method = "dual_kawase";
blur-strength = 10;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

#################################
#        Rounded Corners        #
#################################
corner-radius = 0;

#################################
#            Rules              #
#################################
rules = (
  {
    match = "class_g = 'Alacritty' && focused = true";
    opacity = 0.90;
    blur-background = true;
    blur-background-frame = true;
    blur-background-fixed = true;
    shadow = false;
    fade = true;
  },

  {
    match = "focused = false";
    opacity = 0.70;
    blur-background = true;
    blur-background-frame = true;
    blur-background-fixed = true;
    shadow = false;
    fade = true;
  },

  {
    match = "class_g != 'Alacritty' && focused = true";
    opacity = 1.0;
    blur-background = true;
    blur-background-frame = true;
    blur-background-fixed = true;
    shadow = false;
    fade = true;
  }
);
